-- MySQL Script generated by MySQL Workbench
-- jue 05 mar 2020 20:16:56 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_network` DEFAULT CHARACTER SET utf8 ;
USE `social_network` ;

-- -----------------------------------------------------
-- Table `social_network`.`GENDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`GENDERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMIAL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `GENDER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Users_Genders1_idx` (`GENDER_ID` ASC),
  CONSTRAINT `fk_Users_Genders1`
    FOREIGN KEY (`GENDER_ID`)
    REFERENCES `social_network`.`GENDERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`POSTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE_CREATED` DATETIME NOT NULL,
  `USER_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Posts_Users1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`PHOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`PHOTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FILE_URL` VARCHAR(45) NOT NULL,
  `POST_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Photos_Posts1_idx` (`POST_ID` ASC),
  CONSTRAINT `fk_Photos_Posts1`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `social_network`.`POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`DIRECT_MESSAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`DIRECT_MESSAGES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE_CREATED` DATETIME NOT NULL,
  `RECIEVER_ID` INT NOT NULL,
  `SENDER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DirectMessages_Users1_idx` (`RECIEVER_ID` ASC),
  INDEX `fk_DirectMessages_Users2_idx` (`SENDER_ID` ASC),
  CONSTRAINT `fk_DirectMessages_Users1`
    FOREIGN KEY (`RECIEVER_ID`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirectMessages_Users2`
    FOREIGN KEY (`SENDER_ID`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`MESSAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`MESSAGES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MESSAGE` VARCHAR(45) NOT NULL,
  `DATE_CREATED` DATE NOT NULL,
  `DIRECT_MESSAGE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Messages_DirectMessages1_idx` (`DIRECT_MESSAGE_ID` ASC),
  CONSTRAINT `fk_Messages_DirectMessages1`
    FOREIGN KEY (`DIRECT_MESSAGE_ID`)
    REFERENCES `social_network`.`DIRECT_MESSAGES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`FOLLOWERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`FOLLOWERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `FOLLOWER_ID` INT NOT NULL,
  `FOLLOWED_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Followers_Users1_idx` (`USER_ID` ASC),
  INDEX `fk_Followers_Users2_idx` (`FOLLOWER_ID` ASC),
  CONSTRAINT `fk_Followers_Users1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Followers_Users2`
    FOREIGN KEY (`FOLLOWER_ID`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  `Photos_id` INT NOT NULL,
  `DATE_TAGGED` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tags_Users1_idx` (`Users_id` ASC),
  INDEX `fk_Tags_Photos1_idx` (`Photos_id` ASC),
  CONSTRAINT `fk_Tags_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_Photos1`
    FOREIGN KEY (`Photos_id`)
    REFERENCES `social_network`.`PHOTOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`COMMENTS` (
  `ID` INT NOT NULL,
  `COMMENT` VARCHAR(45) NOT NULL,
  `POST_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Comments_Posts1_idx` (`POST_ID` ASC),
  CONSTRAINT `fk_Comments_Posts1`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `social_network`.`POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`LIKES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_network`.`LIKES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `DATE_LIKED` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Likes_Users1_idx` (`USER_ID` ASC),
  INDEX `fk_Likes_Posts1_idx` (`POST_ID` ASC),
  CONSTRAINT `fk_Likes_Users1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `social_network`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Posts1`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `social_network`.`POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
